name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Dependencies
        run: yarn

      - name: Build Main Process
        run: yarn build:main

      - name: Build Renderer Process
        run: yarn build:renderer

      - name: Build and Release Electron app
        env:
          - GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: yarn release
